### ISSUE TITLE
Workshops: Who are we serving? 

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/gltf-extensions#3]
There are varying levels of complexity associated with our intentions to propose glTF extensions. Who are the key stakeholders involved with approving our proposal and adopting or implementing these glTF extensions? How does this problem break down into motivators, needs, and potential blockers? 

iFire and I got together today, after iFire and humbletim got together over the weekend, to highlight some of these complexities today. We started with a focus on who we are serving, and expanded from there. We believe this may be more productive as a group effort / workshop series. 

I am not sure which workshops to suggest first. As we can run a stakeholder mapping workshop (highlighted on the master OMI backlog) or a user journey map, or a Lightning Decision jam, etc. There are a number of ways this could go, so I suggest we start by getting a recurring meeting series established to break this work down and prioritize our backlog. 

Notes were started [on hackmd](https://hackmd.io/@mrmetaverse/gltf-personas)

**Comment by humbletim** [comment]
notes from 7/21/2021 OMI Weekly Meeting 13: https://hackmd.io/e4RBv8H6TnKfud7ebrvmNQ?both#glTF-extensions-working-group

**Comment by mrmetaverse** [comment]
Curious, do we still feel we need to conduct this workshop? @humbletim @robertlong thoughts? Or should I archive this for now?

**Comment by robertlong** [comment]
No I don't think we do now that we've been operating for over a year.
