### ISSUE TITLE
Mozilla Hubs extension

### ISSUE THREAD

**Issue by fire** [omigroup/gltf-extensions#5]
Thinking a bit about the Mozilla Hubs glTF2 extensions set (For example, what Spoke supports) and the OMI audio emitter glTF2 extension. I believe that we can standardize the Mozilla Hubs extension.

I hope to touch-base on this in our GLTF Extensions meeting today.

**Comment by humbletim** [comment]
summary roll-up of Mozilla Hubs extensions (.components) // source: [MozillaReality/hubs-blender-exporter//default-config.json](https://github.com/MozillaReality/hubs-blender-exporter/blob/bb28096159e1049b6b80da00b1ae1534a6ca0855/default-config.json):


**background** (Scene) 

     color


**fog** (Scene) 

     type, color, near, far, density


**audio-settings** (Scene) 

     avatarDistanceModel, avatarRolloffFactor, avatarRefDistance, avatarMaxDistance, mediaVolume, mediaDistanceModel, mediaRolloffFactor, mediaRefDistance, mediaMaxDistance, mediaConeInnerAngle, mediaConeOuterAngle, mediaConeOuterGain


**visible** (Scene) 

     visible


**directional-light** (Elements) 

     color, intensity, castShadow, shadowMapResolution, shadowBias, shadowRadius


**point-light** (Elements) 

     color, intensity, range, decay, castShadow, shadowMapResolution, shadowBias, shadowRadius


**ambient-light** (Elements) 

     color, intensity


**particle-emitter** (Elements) 

     src, startColor, middleColor, endColor, startOpacity, middleOpacity, endOpacity, sizeCurve, colorCurve, startSize, endSize, sizeRandomness, ageRandomness, lifetime, lifetimeRandomness, particleCount, startVelocity, endVelocity, velocityCurve, angularVelocity


**waypoint** (Elements) 

     canBeSpawnPoint, canBeOccupied, canBeClicked, willDisableMotion, willDisableTeleporting, snapToNavMesh, willMaintainInitialOrientation, willMaintainWorldUp, isOccupied


**uv-scroll** (Animation) 

     speed, increment


**personal-space-invader** (Avatar) 

     radius, useMaterial, invadingOpacity


**link** (Elements) 

     href


**image** (Elements) 

     src, controls, alphaMode, projection


**audio** (Elements) 

     src, autoPlay, controls, loop


**video** (Elements) 

     src, projection, autoPlay, controls, loop


**nav-mesh** (Scene) 

     


**kit** (Architecture Kit) 

     authorName, authorUrl, license


**kit-piece** (Architecture Kit) 

     id, name, tags


**kit-alt-materials** (Architecture Kit) 

     id, name, defaultMaterials, altMaterials


**material-id** (Architecture Kit) 

     id, name


**loop-animation** (Animation) 

     clip, paused


**scale-audio-feedback** (Avatar) 

     minScale, maxScale


**morph-audio-feedback** (Avatar) 

     name, minValue, maxValue


**video-texture-target** (Avatar) 

     targetBaseColorMap, targetEmissiveMap, srcNode


**billboard** (Elements) 

     onlyY


**video-texture-source** (Scene) 

     resolution, fps


**text** (Elements) 

     value, align, baseline, side, whiteSpace, font, color, width, wrapCount, wrapPixels, letterSpacing, lineHeight, opacity, xOffset, zOffset


**ammo-shape** (Scene) 

     type, fit, halfExtents, minHalfExtent, maxHalfExtent, sphereRadius, offset, includeInvisible


**media-frame** (Elements) 

     bounds, mediaType, snapToCenter


**skybox** (Scene) 

     azimuth, inclination, luminance, mieCoefficient, mieDirectionalG, turbidity, rayleigh, distance


**spawner** (Elements) 

     src, mediaOptions


**audio-target** (Elements) 

     srcNode, debug


**zone-audio-source** (Elements) 

     onlyMods, muteSelf, debug


**audio-params** (Elements) 

     audioType, gain, distanceModel, refDistance, rolloffFactor, maxDistance, coneInnerAngle, coneOuterAngle, coneOuterGain


**audio-zone** (Elements) 

     inOut, outIn

**Comment by mrmetaverse** [comment]
@fire do we have an update on the status of this ticket? Is this still "To-Do"?

**Comment by fire** [comment]
I don't think it can be done easily because 1) moz hubs i/o is a moving target 2) we'd need multiple implementors for import and export.

**Comment by robertlong** [comment]
I think we can close this and move all of the extensions we'd like to see proposed to this discussion: https://github.com/omigroup/gltf-extensions/discussions/7

I think we've moved on to standardizing independent extensions rather than formalizing the `MOZ_hubs_components` extension.
