### ISSUE TITLE
Support WAV Audio in OMI_audio_emitter

### ISSUE THREAD

**Issue by robertlong** [omigroup/gltf-extensions#70]
I think we may want to revisit WAV audio support. It has universal support in [web browsers](https://caniuse.com/wav), [Unity](https://docs.unity3d.com/Manual/AudioFiles.html), [Unreal](https://docs.unrealengine.com/4.27/en-US/WorkingWithAudio/WAV/), and [Godot](https://docs.godotengine.org/en/stable/tutorials/assets_pipeline/importing_audio_samples.html).

WAV is the [only audio format supported in MSFT_audio_emitter](https://github.com/KhronosGroup/glTF/blob/8109e86a26c9210814f8d236589ce92a2f9fa8f8/extensions/2.0/Vendor/MSFT_audio_emitter/README.md#clip) and supporting it will allow us to better align with Microsoft's work.

I'm still not sure I support WAV as the only supported audio format though. Ideally you would be able to use either WAV or MP3 in all implementations. MP3 allows us compress audio for bandwidth limited environments like delivering assets on the web.

**Comment by aaronfranke** [comment]
WAV also has the feature of extremely fast decode, so it's usually a better choice for short sound effects (like foosteps) especially where timing is critical (like a gun firing).

**Comment by aaronfranke** [comment]
Fixed by https://github.com/omigroup/gltf-extensions/pull/195
